config/routes.rb
ECCENTRIC::Application.routes.draw do

  resources :displays

  resources :settings

  get "testing/example"
  get "testing/demo"

  root to: 'testing#example'

  resources :map_items
  resources :map_points

  resources :simulations do
    resources :players
  end
  resources :policies
  resources :users

  

end

app/models/simulation.rb
class Simulation < ActiveRecord::Base
	has_many :players, dependent: :destroy
	has_many :policies, through: :players
	validates :name, presence: true, length: { minimum: 5 }
end

app/controllers/simulations_controller.rb
class SimulationsController < ApplicationController
  before_action :set_simulation, only: [:show, :edit, :update, :destroy]

  #http_basic_authenticate_with name: "dhh", password: "secret", except: [:index, :show]

  # GET /simulations
  # GET /simulations.json
  def index
    @simulations = Simulation.all
  end

  # GET /simulations/1
  # GET /simulations/1.json
  def show
  end

  # GET /simulations/new
  def new
    @simulation = Simulation.new
  end

  # GET /simulations/1/edit
  def edit
  end

  # POST /simulations
  # POST /simulations.json
  def create
    @simulation = Simulation.new(simulation_params)

    respond_to do |format|
      if @simulation.save
        format.html { redirect_to @simulation, notice: 'Simulation was successfully created.' }
        format.json { render action: 'show', status: :created, location: @simulation }
      else
        format.html { render action: 'new' }
        format.json { render json: @simulation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /simulations/1
  # PATCH/PUT /simulations/1.json
  def update
    respond_to do |format|
      if @simulation.update(simulation_params)
        format.html { redirect_to @simulation, notice: 'Simulation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @simulation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /simulations/1
  # DELETE /simulations/1.json
  def destroy
    @simulation.destroy
    respond_to do |format|
      format.html { redirect_to simulations_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_simulation
      @simulation = Simulation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def simulation_params
      params.require(:simulation).permit(:simuid, :name)
    end
end

app/helpers/simulations_helper.rb
module SimulationsHelper
end

app/views/simulations/_form.html.erb
<%= form_for(@simulation) do |f| %>
  <% if @simulation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@simulation.errors.count, "error") %> prohibited this simulation from being saved:</h2>

      <ul>
      <% @simulation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/simulations/_slider_bar.html.erb
<ul class="nav nav-list">

    <%= render @simulation.players %>
</ul>

app/views/simulations/edit.html.erb
<div class="container">

	<div class="starter-template">

	<h1>Editing simulation</h1>

	<%= render 'form' %>

	<h2>Players</h2>
	<%= render @simulation.players %>

		<h2>Add a player:</h2>
		<%= form_for([@simulation, @simulation.players.build]) do |f| %>
		  <p>
		    <%= f.label :user_id %><br />
		    <%= f.number_field :user_id %>
		  </p>
		  <p>
		    <%= f.label :roletitle %><br />
		    <%= f.text_field :roletitle %>
		  </p>
		  <p>
		    <%= f.submit %>
		  </p>
		<% end %>

		<%= link_to 'Show', @simulation %> |
		<%= link_to 'Back', simulations_path %>

	</div>
</div><!-- /.container -->

app/views/simulations/index.html.erb
<h1>Listing simulations</h1>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @simulations.each do |simulation| %>
      <tr>
        <td><%= simulation.id %></td>
        <td><%= simulation.name %></td>
        <td><%= link_to 'Show', simulation %></td>
        <td><%= link_to 'Edit', edit_simulation_path(simulation) %></td>
        <td><%= link_to 'Destroy', simulation, :method=>:delete, :class=>:destroy, :confirm => 'Are you sure?' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Simulation', new_simulation_path %>

app/views/simulations/new.html.erb
<h1>New simulation</h1>

<%= render 'form' %>

<%= link_to 'Back', simulations_path %>

app/views/simulations/show.html.erb
<div class="container"
  style="position: absolute; width: 20%; background: #ffffff; border:4px solid black">

  <%= render :partial => '/simulations/slider_bar' %>
</div>

<div class="container"
  style="position: absolute; margin-left: 20%; width: 60%">

<!-- Example row of columns -->
<div class="row">
    <div class="col-sm-12">
      <%= render :partial => '/displays/display_table' %>
    </div>
</div>
<hr>

<div class="row">
    <div class="col-sm-12">
          <h1><%= @simulation.name %></h1>
          <p id="notice"><%= notice %></p>
    </div>
</div>
<hr>

<!-- <%= render @simulation.players %>/ -->

<div class="row">
    <div class="col-sm-12">
      <%= link_to 'Edit', edit_simulation_path(@simulation) %> |
      <%= link_to 'Back', simulations_path %> 
    </div>
</div>
<hr>

<footer>
  <p>&copy; Something 2013</p>
</footer>

</div><!-- /.container -->

<%= javascript_tag do %>
  test = '<%= j settings_url %>';
<% end %>

<script>
  var emmision = [];
  var supply = [];
  var demand = [];
  <% Setting.all.each do |setting| %>
    emmision[<%= setting.id %>] = <%= setting.lin_emmision %>
    supply[<%= setting.id %>]  = <%= setting.lin_supply %>
    demand[<%= setting.id %>]  = <%= setting.lin_demand %>
  <% end %>

  var impact = 0.5;
  var total_emmisions = 0;
  var total_supply = 0;
  var total_demand = 0;

  var slider_values = [];

  $(document).ready(function(){
    $('.carousel').carousel({
            interval: false
        });

    // produce sliders
    var sliders = document.getElementsByClassName('slider');
    for (var i = 0; i < sliders.length; ++i) {
      var item = sliders[i];
      slider_values[item.id] = document.getElementById("v"+item.id).innerHTML / 100;
      
      $(item).slider( { 
        value: document.getElementById("v"+item.id).innerHTML,


        change: function(e, ui){
          var txt = document.getElementById("v"+this.id);


          //Do something with ui.value
          txt.innerHTML = ui.value;
          $.ajax('/policies/'+this.id, {
            type: 'PATCH',
            data: { policy: { value: ui.value }, commit: "Update Policy" },
            //success: function() { .. },
            error: function() { alert("err"); }
          });

          impact = (ui.value / 100) * emmision[this.id];
          slider_values[this.id] = ui.value / 100;
          update_values();
          update_display();

        } 
      });
    }
    update_values();
    setup_display();
  });

  function update_values() {
    total_emmisions = 0.0;
    total_supply = 1.0;
    total_demand = 1.0;

    for (var i = 1; i < slider_values.length; ++i) {
      total_emmisions += slider_values[i] * emmision[i];
      total_supply += slider_values[i] * supply[i];
      total_demand += slider_values[i] * demand[i];
    }
  }


</script>