config/routes.rb
ECCENTRIC::Application.routes.draw do

  resources :displays

  resources :settings

  get "testing/example"
  get "testing/demo"

  root to: 'testing#example'

  resources :map_items
  resources :map_points

  resources :simulations do
    resources :players
  end
  resources :policies
  resources :users

  

end

app/models/display.rb
class Display < ActiveRecord::Base
end

app/controllers/displays_controller.rb
class DisplaysController < ApplicationController
  before_action :set_display, only: [:show, :edit, :update, :destroy]

  # GET /displays
  # GET /displays.json
  def index
    @displays = Display.all
  end

  # GET /displays/1
  # GET /displays/1.json
  def show
  end

  # GET /displays/new
  def new
    @display = Display.new
  end

  # GET /displays/1/edit
  def edit
  end

  # POST /displays
  # POST /displays.json
  def create
    @display = Display.new(display_params)

    respond_to do |format|
      if @display.save
        format.html { redirect_to @display, notice: 'Display was successfully created.' }
        format.json { render action: 'show', status: :created, location: @display }
      else
        format.html { render action: 'new' }
        format.json { render json: @display.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /displays/1
  # PATCH/PUT /displays/1.json
  def update
    respond_to do |format|
      if @display.update(display_params)
        format.html { redirect_to @display, notice: 'Display was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @display.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /displays/1
  # DELETE /displays/1.json
  def destroy
    @display.destroy
    respond_to do |format|
      format.html { redirect_to displays_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_display
      @display = Display.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def display_params
      params.require(:display).permit(:name, :group, :pathname)
    end
end

class Graph < DisplaysController
  def create
    @display = Graph.new(display_params)

    respond_to do |format|
      if @display.save
        format.html { redirect_to @display, notice: 'Display was successfully created.' }
        format.json { render action: 'show', status: :created, location: @display }
      else
        format.html { render action: 'new' }
        format.json { render json: @display.errors, status: :unprocessable_entity }
      end
    end
  end
end

class Image < DisplaysController
end

app/helpers/displays_helper.rb
module DisplaysHelper
end

app/views/displays/_display.html.erb
<%= image_tag "/images/nz_map.png" %>

app/views/displays/_display_table.html.erb
<!--  Carousel - consult the Twitter Bootstrap docs at
      http://twitter.github.com/bootstrap/javascript.html#carousel -->
<div id="this-carousel-id" class="carousel slide"><!-- class of slide for animation -->
  <div class="carousel-inner">
      <!-- class of active since it's the first item -->
      <!--<div class="item"> 
        <img src="http://placehold.it/1200x780" alt="" width="100%" />
        <div class="carousel-caption">
          <p>Caption text here</p>
        </div>
      </div>-->

      <div class="item active">
        <%= render 'displays/simple_graph' %>
        <div class="carousel-caption">
          <p>Graph</p>
        </div>
      </div>

      <div class="item">
        <%= render 'displays/test' %>
        <div class="carousel-caption">
          <p>NZ Map</p>
        </div>
      </div>

      <div class="item">
        <%= render 'displays/reaction' %>
      </div>

    </div><!-- /.carousel-inner -->
  <!--  Next and Previous controls below
        href values must reference the id for this carousel -->
    <a class="carousel-control left" href="#this-carousel-id" data-slide="prev">&lsaquo;</a>
    <a class="carousel-control right" href="#this-carousel-id" data-slide="next">&rsaquo;</a>
</div><!-- /.carousel -->

<script>
function setup_display() {
  setup_graph();
  setup_map();
  refreshReaction();
}

function update_display() {

  update_graph();
  update_map();
  refreshReaction();
  update_map();
}

</script>

app/views/displays/_display_table_back_up.html.erb
<head>

  <style type="text/css">
    body, html {
        height: 100%;
        overflow: hidden;
    }

    .navbar-inner {
        height: 40px;
    }

    .scrollable {
        height: 100%;
        overflow: auto;
    }

    .max-height {
        height: 100%;
    }

    .no-overflow {
        overflow: hidden;
    }

    .pad40-top {
        padding-top: 40px;
    }
  </style>
</head>

<div class="row">
  <div class="col-lg-6" style="width: 100%">
    <%= render 'displays/test' %>

  </div>
</div>

<div class="container max-height no-overflow">
  <div class="row max-height">
    <div class="span4 scrollable">
      <div class="pad40-top">
        right sidebar contents
        right sidebar contents
        right sidebar contents
        right sidebar contents
        right sidebar contents
        right sidebar contents
        right sidebar contents
        right sidebar contents
        right sidebar contents
        right sidebar contents
        right sidebar contents
        right sidebar contents
        right sidebar contents
        right sidebar contents
        right sidebar contents
        right sidebar contents
        right sidebar contents
        right sidebar contents
        right sidebar contents
        right sidebar contents
        right sidebar contents
        right sidebar contents
        right sidebar contents
        right sidebar contents
        right sidebar contents
        right sidebar contents
        right sidebar contents
        right sidebar contents
        right sidebar contents
        right sidebar contents
        right sidebar contents
        right sidebar contents
        right sidebar contents
        right sidebar contents
        right sidebar contents
        right sidebar contents
        right sidebar contents
        right sidebar contents
        right sidebar contents
        right sidebar contents
        right sidebar contents
        right sidebar contents
        right sidebar contents
        right sidebar contents
        right sidebar contents
        right sidebar contents
        right sidebar contents
        right sidebar contents
        right sidebar contents
      </div>
    </div>
  </div>
</div>

<script>
function setup_display() {
  setup_graph();
  setup_map();
}

function update_display() {
  update_graph();
  update_map();
}

</script>

app/views/displays/_form.html.erb
<%= form_for(@display) do |f| %>
  <% if @display.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@display.errors.count, "error") %> prohibited this display from being saved:</h2>

      <ul>
      <% @display.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :group %><br>
    <%= f.number_field :group %>
  </div>
  <div class="field">
    <%= f.label :pathname %><br>
    <%= f.text_field :pathname %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/displays/_graph.html.erb
<%= javascript_include_tag "http://d3js.org/d3.v3.min.js", charset: "utf-8" %>
<div id="data_field"></div>

<script>

var n = 4, // number of layers
    m = 200, // number of samples per layer
    stack,
    layers0,
    layers1;

var width = 1200,
    height = 780;

var svg = d3.select("#data_field").append("svg")
    .attr("width", width)
    .attr("height", height);

var area;


function setup_graph() {

    stack = d3.layout.stack().offset("wiggle");
    layers0 = stack(d3.range(n).map(function() { return bumpLayer(m); }));
    layers1 = stack(d3.range(n).map(function() { return bumpLayer(m); }));

var color = d3.scale.linear()
    .range(["#aad", "#556"]);

var x = d3.scale.linear()
    .domain([0, m - 1])
    .range([0, width]);

var y = d3.scale.linear()
    .domain([0, d3.max(layers0.concat(layers1), function(layer) { return d3.max(layer, function(d) { return d.y0 + d.y; }); })])
    .range([height, 0]);

area = d3.svg.area()
    .x(function(d) { return x(d.x); })
    .y0(function(d) { return y(d.y0); })
    .y1(function(d) { return y(d.y0 + d.y); });


svg.selectAll("path")
    .data(layers0)
  .enter().append("path")
    .attr("d", area)
    .style("fill", function() { return color(Math.random()); });

}

function update_graph() {
  svg.selectAll("path")
    .data(function() {
        return stack(d3.range(n).map(function() { return bumpLayer(m); }));
      })
    .transition()
      .duration(2500)
      .attr("d", area);;
}

function transition() {
  d3.selectAll("path")
      .data(function() {
        var d = layers1;
        layers1 = layers0;
        return layers0 = d;
      })
    .transition()
      .duration(2500)
      .attr("d", area);
}

// Inspired by Lee Byron's test data generator.
function bumpLayer(n) {

  function bump(a) {
    var x = 1 / (.1 + total_emmisions), // Math.random()
        y = 2 * 0.5 - .5,
        z = 10 / (.1 + 0.5);
    for (var i = 0; i < n; i++) {
      var w = (i / n - y) * z;
      a[i] += x * Math.exp(-w * w);
    }
  }

  var a = [], i;
  for (i = 0; i < n; ++i) a[i] = 0;
  for (i = 0; i < 5; ++i) bump(a);
  return a.map(function(d, i) { return {x: i, y: Math.max(0, d)}; });
}

</script>

app/views/displays/_reaction.html.erb
<style>
  #reaction_bar{
     height:auto !important;
     text-align: center;
  }
</style>

<div id="reaction_bar" width="100%">

            <div id="reaction_title"
                style="font-size: 300%; padding-top:5%">
                Reactions</div>
            <img id="face" src="/images/sad.png" alt: "reaction">
            <div id="comment_title" style="font-size: 250%; padding-top: 5%">
                Citizens are saying: </div>
            <div style="font-size: 150%"> 
                <div id="comment_1">'My t.v. has no power'</div>
                <div id="comment_2">'cough cough'</div>
                <div id="comment_3">'I like turtles'</div>
            </div>
            
</div>

<script type="text/javascript">

  function refreshReaction(){
  //change the reaction
    if (total_supply >= total_demand && total_emmisions < 0.6) {

        //document.getElementById("face").innerHTML = ":)";
        document.getElementById("face").src="../images/happy.png";
    }
    else {

        //document.getElementById("face").innerHTML = ":(";
        document.getElementById("face").src="../images/sad.png";
    }

    //change what people are saying
    if (total_supply < total_demand / 2) {

        document.getElementById("comment_1").innerHTML =
            "\'My husband who was in a coma died when his life " +
            "support ran out of power\'";
    }
    else if (total_supply < total_demand / 1.7) {

        document.getElementById("comment_1").innerHTML =
            "\'My kitchen has a layer of ice on the floor since " + 
            "I can\'t turn my heater on.\'";
    }
    else if (total_supply < total_demand / 1.3) {

        document.getElementById("comment_1").innerHTML =
            "\'My t.v. has no power\'";
    }
    else if (total_supply < total_demand) {

        document.getElementById("comment_1").innerHTML =
            "\'There\'s not enough power for my private render farm\'";
    }
    else if (total_supply > total_demand * 1.5) {

        document.getElementById("comment_1").innerHTML =
        "\'SOOO MUCH POWER!\'";
    }
    else {

        document.getElementById("comment_1").innerHTML =
            "\'The level of power is sufficient\'";
    }

    if (total_emmisions < 0.2) {

        document.getElementById("comment_2").innerHTML =
            "\'The air is so pure I'm aging backwards\'";
    }
    else if (total_emmisions < 0.4) {

        document.getElementById("comment_2").innerHTML =
            "\'The air is so clean!\'";
    }
    else if (total_emmisions < 0.6) {

        document.getElementById("comment_2").innerHTML =
            "\'cough cough\'";
    }
    else if (total_emmisions < 0.8) {

        document.getElementById("comment_2").innerHTML =
            "\'I think I have the black lung\'";
    }
    else {

        document.getElementById("comment_2").innerHTML =
            "\'I lost my daughter in a cloud of carbon\'";
    }

  }

</script>

app/views/displays/_simple_graph.html.erb
<%= javascript_include_tag "http://d3js.org/d3.v3.min.js", charset: "utf-8" %>
<center>
<div class='chart' id='chart-2'>
</div>
</center>

<script type='text/javascript'>
var data = [32, 57, 112],
    dataEnter = data.concat(293),
    dataExit = data.slice(0, 2),
    w = 700,
    h = 500,
    x = d3.scale.ordinal().domain([57, 32, 112]).rangePoints([0, w], 1),
    y = d3.scale.ordinal().domain(data).rangePoints([0, h], 2);


var svg = d3.select("#chart-2").append("svg")
      .attr("width", w)
      .attr("height", h);

function setup_graph() {

   var e = svg.selectAll("emmisions").data("emmisions")
    .enter()
    	.append("circle")
      	.attr("class", "emmisions")
      	.attr("cx", 230)
      	.attr("cy", 120)
      	.attr("r", 100*total_emmisions)
      	.style("fill", "gray");

    e.append("text")
    	.attr("dx", 12)
      	.attr("dy", ".35em")
     	.attr("text-anchor", "middle")
     	.text("Emissions");

 	svg.selectAll("supply").data("supply")
    .enter().append("circle")
      .attr("class", "supply")
      .attr("cx", 530)
      .attr("cy", 130)
      .attr("r", 100*total_supply)
      .style("fill", "green");

   	svg.selectAll("demand").data("demand")
    .enter().append("circle")
      .attr("class", "demand")
      .attr("cx", 380)
      .attr("cy", 330)
      .attr("r", 100*total_demand)
      .style("fill", "red");
}

function update_graph() {
	  svg.selectAll(".emmisions").data("emissions").attr("r", 100*total_emmisions).transition().duration(3000);
      svg.selectAll(".supply").data("supply").attr("r", 100*total_supply).transition().duration(3000);
      svg.selectAll(".demand").data("demand").attr("r", 100*total_demand).transition().duration(3000);
}

</script>

app/views/displays/_test.html.erb
<style>
#nz_map {
    padding: inherit;
    margin: inherit;
    margin-left: 25%;
    user-select: none;
}

#clouds {
    padding: inherit;
    margin: inherit;
    margin-left: 25%;
    position: absolute;
    user-select: none;
}
</style>

<img id="nz_map" src="/images/nz_map.png", alt="New Zealand map", width="400px">
<img id="clouds" src="/images/clouds.png", alt="clouds", width="400px">


<script>
var cloudOpUp = true;

function setup_map() {
    right_x = $("#nz_map").offset().left;
    right_y = $("#nz_map").offset().top;

    $("#clouds").css({
        opacity: total_emmisions,
        left:right_x + 'px', 
        top:right_y + 'px'
    });
}

function update_map() {
    $("#clouds").css({opacity: total_emmisions});
}

$("#clouds").onclick = function() {

    //change clouds opacity
    if (cloudOpUp) {
        impact += 0.1;
    }
    else {
        impact -= 0.1;
    }
    if (impact < 0.0) {
        cloudOpUp = true;
        impact = 0.0;
    }
    else if (impact > 1.0) {
        cloudOpUp = false;
        impact = 1.0;
    }

    update_map();
};

</script>

app/views/displays/edit.html.erb
<h1>Editing display</h1>

<%= render 'form' %>

<%= link_to 'Show', @display %> |
<%= link_to 'Back', displays_path %>

app/views/displays/index.html.erb
<%= render 'display_table' %>

<h1>Listing displays</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Group</th>
      <th>Pathname</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @displays.each do |display| %>
      <tr>
        <td><%= display.name %></td>
        <td><%= display.group %></td>
        <td><%= display.pathname %></td>
        <td><%= link_to 'Show', display %></td>
        <td><%= link_to 'Edit', edit_display_path(display) %></td>
        <td><%= link_to 'Destroy', display, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Display', new_display_path %>

app/views/displays/new.html.erb
<h1>New display</h1>

<%= render 'form' %>

<%= link_to 'Back', displays_path %>

app/views/displays/show.html.erb
<p id="notice"><%= notice %></p>

<%= render 'display' %>

<p>
  <strong>Name:</strong>
  <%= @display.name %>
</p>

<p>
  <strong>Group:</strong>
  <%= @display.group %>
</p>

<p>
  <strong>Pathname:</strong>
  <%= @display.pathname %>
</p>

<%= link_to 'Edit', edit_display_path(@display) %> |
<%= link_to 'Back', displays_path %>